# Build project, export static content and push to deployment branch

name: Deploy GitHub Page

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 10 * * 1" # Every Monday at 10AM UTC

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Get files
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run Tests
        run: npm run test:ci

      - name: Add .nojekyll file
        run: touch ./out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: out
